#!/usr/bin/env bash
# Install nginx on your web server
# Nginx should listen on port 80
# When quering nginc at its root / with a Get request
# Using curl, it must return a page that contains the string Holberton School

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!"> /var/www/html/index.html
service nginx start
