#!/usr/bin/env bash
# configure the nginx server so that /redirect_me is redirected to another page.
# The redirection is configured as a "301 moved permanntly"

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.htm;
	location /redirect_me {
		return 301 https:/www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
