#!/usr/bin/env bash
# Iterate through all running processes in the /proc directory
for pid_dir in /proc/*/; do
    pid=$(basename "$pid_dir")
    
    if [ -f "$pid_dir/status" ]; then
        process_name=$(awk '/Name/ {print $2}' "$pid_dir/status")
        
        if [[ "$process_name" == *bash* ]]; then
            echo "$pid $process_name"
        fi
    fi
done

